query DetailTimelinePage(
  $owner: String!
  $name: String!
  $number: Int!
  $after: String
) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      timelineItems(first: 50, after: $after, itemTypes: [
        PULL_REQUEST_COMMIT,
        ISSUE_COMMENT,
        PULL_REQUEST_REVIEW,
        HEAD_REF_FORCE_PUSHED_EVENT,
        MERGED_EVENT, CLOSED_EVENT, REOPENED_EVENT
      ]) {
        pageInfo { hasNextPage endCursor }
        nodes {
          __typename
          ... on PullRequestCommit {
            commit {
              oid
              messageHeadline
              pushedDate
              author { user { login } name }
            }
          }
          ... on IssueComment {
            id author { login } body createdAt
          }
          ... on PullRequestReview {
            id author { login } state body submittedAt
          }
          ... on HeadRefForcePushedEvent {
            createdAt actor { login }
            beforeCommit { oid }
            afterCommit { oid }
          }
          ... on MergedEvent {
            createdAt actor { login }
            commit { oid }
          }
          ... on ClosedEvent {
            createdAt actor { login }
          }
          ... on ReopenedEvent {
            createdAt actor { login }
          }
        }
      }
    }
  }
}
